[[chains]]
name = "injective-mainnet"
displayname = "Injective-mainnet"
chain-id = "injective-1"
rpc = "https://injective-rpc.polkachu.com/"
api = "https://injective-api.polkachu.com/"
version = "v1beta1"
proposal_link = "https://www.mintscan.io/injective/proposals/"

[[chains]]
name = "evmos-mainnet"
displayname = "Evmos-mainnet"
chain-id = "evmos_9001-2"
rpc = "https://evmos-mainnet.public.blastapi.io/443"
api = "https://api.evmos.chaintools.tech"
version = "v1"
proposal_link = "https://www.mintscan.io/evmos/proposals/"

[[chains]]
name = "evmos-testnet"
displayname = "Evmos-testnet"
chain-id = "evmos_9000-4"
rpc = "https://rpc-t.evmos.nodestake.top"
api = "https://api-t.evmos.nodestake.top"
version = "v1"
proposal_link = "https://testnet.evmos.explorers.guru/proposal/"

[[chains]]
name = "haqq_testnet"
displayname = "Haqq-testnet"
chain-id = "haqq_54211-3"
rpc = "https://rpc.tm.testedge.haqq.network"
api = "https://haqq-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://haqq.explorers.guru/proposal/"

[[chains]]
name = "sifchain"
displayname = "SifChain"
chain-id = "sifchain-1"
rpc = "https://rpc.sifchain.finance:443"
api = "https://api.sifchain.finance:443"
version = "v1beta1"
proposal_link = "https://www.mintscan.io/sifchain/proposals/"

[[chains]]
name = "xpla-mainnet"
displayname = "XPLA-Mainnet"
chain-id = "Dimension_37-1"
rpc = "https://dimension-rpc.xpla.dev"
api = "https://dimension-lcd.xpla.dev"
version = "v1beta1"
proposal_link = "https://explorer.xpla.io/mainnet/proposal/"

[[chains]]
name = "xpla-testnet"
displayname = "XPLA-testnet"
chain-id = "Cube_47-5"
rpc = "https://cube-rpc.xpla.dev/"
api = "https://cube-lcd.xpla.dev/"
version = "v1beta1"
proposal_link = "https://explorer.xpla.io/testnet/proposal/"

[[chains]]
name = "umme-testnet"
displayname = "Umee-Testnet"
chain-id = "canon-2"
rpc = "https://umee-testnet-rpc.polkachu.com/"
api = "https://umee-testnet-api.polkachu.com"
version = "v1"
proposal_link = "https://explorer.stavr.tech/umee-canon/gov/"

[[chains]]
name = "umee-mainnet"
displayname = "Umee-Mainnet"
chain-id = "umee-1"
rpc = "https://umee-rpc.polkachu.com"
api = "https://umee-api.polkachu.com"
version = "v1beta1"
proposal_link = "https://www.mintscan.io/umee/proposals/"

[[chains]]
name = "persistence-testnet"
displayname = "Persistent-Testnet"
chain-id = "test-core-1"
rpc = "https://persistence-testnet-rpc.polkachu.com/"
api = "https://rest.testnet.persistence.one"
version = "v1beta1"
proposal_link = "https://testnet.mintscan.io/persistence-testnet/proposals/"

[[chains]]
name = "persistence-mainnet"
displayname = "Persistence-Mainnet"
chain-id = "core-1"
rpc = "https://persistence-rpc.polkachu.com"
api = "https://persistence-api.polkachu.com"
version = "v1beta1"
proposal_link = "https://www.mintscan.io/persistence/proposals/"

[[chains]]
name = "okp4-testnet"
displayname = "OKP4-Testnet"
chain-id = "okp4-nemeton-1"
rpc = "https://okp4-testnet-rpc.polkachu.com"
api = "https://okp4-testnet-api.polkachu.com"
version = "v1"
proposal_link = "https://okp4.explorers.guru/proposal/"

[[chains]]
name = "axelar-testnet"
displayname = "Axelar-Testnet"
chain-id = "axelar-testnet-lisbon-3"
rpc = "https://axelar-testnet-rpc.polkachu.com"
api = "https://axelar-testnet-api.polkachu.com"
version = "v1beta1"
proposal_link = "https://testnet.mintscan.io/axelar-testnet/proposals/"

[[chains]]
name = "celestia-testnet"
displayname = "Celestia-Testnet"
chain-id = "mocha"
rpc = "https://rpc-mocha.pops.one"
api = "https://api-mocha.pops.one"
version = "v1beta1"
proposal_link = "https://testnet.mintscan.io/celestia-testnet/proposals/"

[[chains]]
name = "celestia-blockspacerace"
displayname = "Celestia-Blockspacerace"
chain-id = "blockspacerace"
rpc = "https://celestia-testnet.rpc.kjnodes.com"
api = "https://celestia-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://testnet.mintscan.io/celestia-incentivized-testnet/proposals/"

[[chains]]
name = "axelar-mainnet"
displayname = "Axelar-Mainnet"
chain-id = "axelar-dojo-1"
rpc = "https://axelar-rpc.polkachu.com"
api = "https://axelar-api.polkachu.com"
version = "v1beta1"
proposal_link = "https://www.mintscan.io/axelar/proposals/"

[[chains]]
name = "nolus-testnet"
displayname = "Nolus-Testnet"
chain-id = "nolus-rila"
rpc = "https://nolus-testnet.rpc.kjnodes.com"
api = "https://nolus-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://nolus.explorers.guru/proposal/"

[[chains]]
name = "agoric-mainnet"
displayname = "Agoric-Mainnet"
chain-id = "agoric-3"
rpc = "https://agoric.rpc.kjnodes.com"
api = "https://agoric.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://bigdipper.live/agoric/proposals/"

[[chains]]
name = "uptick-tesnet"
displayname = "Uptick-Testnet"
chain-id = "uptick_7000-2"
rpc = "https://uptick-testnet.rpc.kjnodes.com"
api = "https://uptick-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://testnet.uptick.explorers.guru/proposal/"

[[chains]]
name = "uptick-mainnet"
displayname = "Uptick-Mainnet"
chain-id = "uptick_117-1"
rpc = "https://uptick.rpc.kjnodes.com"
api = "https://uptick.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://uptick.explorers.guru/proposal/"

[[chains]]
name = "dymension-tesnet"
displayname = "Dymension-Testnet"
chain-id = "35-C"
rpc = "https://dymension-testnet.rpc.kjnodes.com/"
api = "https://dymension-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://dymension.explorers.guru/proposal/"

[[chains]]
name = "aura-mainnet"
displayname = "Aura-Mainnet"
chain-id = "xstaxy-1"
rpc = "https://aura.rpc.kjnodes.com/"
api = "https://aura.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://aurascan.io/votings/"

[[chains]]
name = "aura-testnet"
displayname = "Aura-Testnet"
chain-id = "euphoria-2"
rpc = "https://aura-testnet.api.kjnodes.com/"
api = "https://aura-testnet.api.kjnodes.com"
version = "v1beta1"
proposal_link = "https://euphoria.aurascan.io/votings/"